/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_abc_berkeley_PWTC */

#ifndef _Included_edu_abc_berkeley_PWTC
#define _Included_edu_abc_berkeley_PWTC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_abc_berkeley_PWTC
 * Method:    parallelWriteTiff
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;IIII)V
 */
JNIEXPORT void JNICALL Java_edu_abc_berkeley_PWTC_parallelWriteTiff
  (JNIEnv *, jobject, jstring, jobjectArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
