/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_abc_berkeley_PWZC */

#ifndef _Included_edu_abc_berkeley_PWZC
#define _Included_edu_abc_berkeley_PWZC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_abc_berkeley_PWZC
 * Method:    parallelWriteZarr
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;JJJJJJJJJILjava/lang/String;IJ)V
 */
JNIEXPORT void JNICALL Java_edu_abc_berkeley_PWZC_parallelWriteZarr
  (JNIEnv *, jobject, jstring, jobjectArray, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jint, jstring, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
