/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_abc_berkeley_PRZC */

#ifndef _Included_edu_abc_berkeley_PRZC
#define _Included_edu_abc_berkeley_PRZC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_abc_berkeley_PRZC
 * Method:    parallelReadZarrUINT8
 * Signature: (Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_abc_berkeley_PRZC_parallelReadZarrUINT8
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRZC
 * Method:    parallelReadZarrUINT16
 * Signature: (Ljava/lang/String;)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_edu_abc_berkeley_PRZC_parallelReadZarrUINT16
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRZC
 * Method:    parallelReadZarrFLOAT
 * Signature: (Ljava/lang/String;)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_edu_abc_berkeley_PRZC_parallelReadZarrFLOAT
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRZC
 * Method:    parallelReadZarrDOUBLE
 * Signature: (Ljava/lang/String;)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_edu_abc_berkeley_PRZC_parallelReadZarrDOUBLE
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRZC
 * Method:    getDataType
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_abc_berkeley_PRZC_getDataType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRZC
 * Method:    getImageDims
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_abc_berkeley_PRZC_getImageDims
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
