/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_abc_berkeley_PRTC */

#ifndef _Included_edu_abc_berkeley_PRTC
#define _Included_edu_abc_berkeley_PRTC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_abc_berkeley_PRTC
 * Method:    parallelReadTiffC
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_edu_abc_berkeley_PRTC_parallelReadTiffC
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     edu_abc_berkeley_PRTC
 * Method:    parallelReadTiffUINT8
 * Signature: (Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_abc_berkeley_PRTC_parallelReadTiffUINT8
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRTC
 * Method:    parallelReadTiffUINT16
 * Signature: (Ljava/lang/String;)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_edu_abc_berkeley_PRTC_parallelReadTiffUINT16
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRTC
 * Method:    parallelReadTiffFLOAT
 * Signature: (Ljava/lang/String;)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_edu_abc_berkeley_PRTC_parallelReadTiffFLOAT
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRTC
 * Method:    parallelReadTiffDOUBLE
 * Signature: (Ljava/lang/String;)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_edu_abc_berkeley_PRTC_parallelReadTiffDOUBLE
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRTC
 * Method:    getDataType
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_abc_berkeley_PRTC_getDataType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_abc_berkeley_PRTC
 * Method:    getImageDims
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_edu_abc_berkeley_PRTC_getImageDims
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
